"""US city/town names. Parks, restaurants, and time zones are not cities."""

US_CITIES = frozenset(
    {
        "akron",
        "albany",
        "albuquerque",
        "alexandria",
        "allentown",
        "amarillo",
        "anaheim",
        "anchorage",
        "ann arbor",
        "arlington",
        "atlanta",
        "augusta",
        "aurora",
        "austin",
        "bakersfield",
        "baltimore",
        "baton rouge",
        "bellevue",
        "birmingham",
        "boise",
        "boston",
        "boulder",
        "bridgeport",
        "buffalo",
        "burbank",
        "cambridge",
        "cape coral",
        "carrollton",
        "cary",
        "cedar rapids",
        "chandler",
        "charleston",
        "charlotte",
        "chattanooga",
        "chesapeake",
        "chicago",
        "chula vista",
        "cincinnati",
        "clarksville",
        "cleveland",
        "colorado springs",
        "columbia",
        "columbus",
        "concord",
        "coral springs",
        "corona",
        "corpus christi",
        "dallas",
        "dayton",
        "denver",
        "des moines",
        "detroit",
        "durham",
        "el paso",
        "elk grove",
        "escondido",
        "eugene",
        "evansville",
        "fairfield",
        "fargo",
        "fayetteville",
        "fontana",
        "fort collins",
        "fort lauderdale",
        "fort wayne",
        "fort worth",
        "fremont",
        "fresno",
        "frisco",
        "fullerton",
        "gainesville",
        "garland",
        "gilbert",
        "glendale",
        "grand prairie",
        "grand rapids",
        "greensboro",
        "henderson",
        "hialeah",
        "hollywood",
        "honolulu",
        "houston",
        "huntington beach",
        "huntsville",
        "independence",
        "indianapolis",
        "irvine",
        "irving",
        "jackson",
        "jacksonville",
        "jersey city",
        "joliet",
        "kansas city",
        "knoxville",
        "lafayette",
        "lakeland",
        "lakewood",
        "lancaster",
        "laredo",
        "las vegas",
        "lexington",
        "lincoln",
        "little rock",
        "long beach",
        "los angeles",
        "louisville",
        "lubbock",
        "madison",
        "manchester",
        "mcallen",
        "mckinney",
        "memphis",
        "mesa",
        "mesquite",
        "miami",
        "milwaukee",
        "minneapolis",
        "mobile",
        "modesto",
        "montgomery",
        "moreno valley",
        "murfreesboro",
        "naperville",
        "nashville",
        "new haven",
        "new orleans",
        "new york",
        "newark",
        "newport news",
        "norfolk",
        "norman",
        "north las vegas",
        "oakland",
        "oceanside",
        "oklahoma city",
        "omaha",
        "ontario",
        "orlando",
        "overland park",
        "oxnard",
        "palmdale",
        "pasadena",
        "paterson",
        "pembroke pines",
        "peoria",
        "philadelphia",
        "phoenix",
        "pittsburgh",
        "plano",
        "pomona",
        "port st lucie",
        "portland",
        "providence",
        "provo",
        "raleigh",
        "rancho cucamonga",
        "reno",
        "richmond",
        "riverside",
        "rochester",
        "rockford",
        "sacramento",
        "salem",
        "salinas",
        "salt lake city",
        "san antonio",
        "san bernardino",
        "san diego",
        "san francisco",
        "san jose",
        "santa ana",
        "santa clara",
        "santa clarita",
        "santa rosa",
        "savannah",
        "scottsdale",
        "seattle",
        "shreveport",
        "sioux falls",
        "spokane",
        "springfield",
        "st louis",
        "st paul",
        "st petersburg",
        "stamford",
        "sterling heights",
        "stockton",
        "sunnyvale",
        "syracuse",
        "tacoma",
        "tallahassee",
        "tampa",
        "tempe",
        "thornton",
        "thousand oaks",
        "toledo",
        "topeka",
        "torrance",
        "tucson",
        "tulsa",
        "vancouver",
        "virginia beach",
        "visalia",
        "waco",
        "warren",
        "washington",
        "wichita",
        "wilmington",
        "winston salem",
        "worcester",
        "yonkers",
    }
)

NOT_A_CITY_MARKERS = (
    "park",
    "restaurant",
    "cafe",
    "coffee shop",
    "mall",
    "plaza",
    "stadium",
    "arena",
    "airport",
    "hotel",
    "motel",
    "bar",
    "club",
    "walmart",
    "target",
    "mcdonald",
    "beach",
    "pier",
    "zoo",
    "museum",
    "theme park",
    "amusement",
    "gas station",
    "truck stop",
    "campus",
    "university",
    "high school",
    "apartment",
    "condo",
    "neighborhood",
    "suburb of",
)

TIMEZONE_MARKERS = (
    "timezone",
    "time zone",
    "eastern time",
    "central time",
    "mountain time",
    "pacific time",
    "alaska time",
    "hawaii time",
)
TIMEZONE_CODES = frozenset(
    {"est", "edt", "cst", "cdt", "mst", "mdt", "pst", "pdt", "akst", "akdt", "hst", "utc", "gmt"}
)
