"""US city/town names. Parks, restaurants, and time zones are not cities."""

US_CITIES = frozenset(
    {
        "akron",
        "albany",
        "albuquerque",
        "alexandria",
        "allentown",
        "amarillo",
        "anaheim",
        "anchorage",
        "ann arbor",
        "arlington",
        "atlanta",
        "augusta",
        "aurora",
        "austin",
        "bakersfield",
        "baltimore",
        "baton rouge",
        "bellevue",
        "birmingham",
        "boise",
        "boston",
        "boulder",
        "bridgeport",
        "buffalo",
        "burbank",
        "cambridge",
        "cape coral",
        "carrollton",
        "cary",
        "cedar rapids",
        "chandler",
        "charleston",
        "charlotte",
        "chattanooga",
        "chesapeake",
        "chicago",
        "chula vista",
        "cincinnati",
        "clarksville",
        "cleveland",
        "colorado springs",
        "columbia",
        "columbus",
        "concord",
        "coral springs",
        "corona",
        "corpus christi",
        "dallas",
        "dayton",
        "denver",
        "des moines",
        "detroit",
        "durham",
        "el paso",
        "elk grove",
        "escondido",
        "eugene",
        "evansville",
        "fairfield",
        "fargo",
        "fayetteville",
        "fontana",
        "fort collins",
        "fort lauderdale",
        "fort wayne",
        "fort worth",
        "fremont",
        "fresno",
        "frisco",
        "fullerton",
        "gainesville",
        "garland",
        "gilbert",
        "glendale",
        "grand prairie",
        "grand rapids",
        "greensboro",
        "henderson",
        "hialeah",
        "hollywood",
        "honolulu",
        "houston",
        "huntington beach",
        "huntsville",
        "independence",
        "indianapolis",
        "irvine",
        "irving",
        "jackson",
        "jacksonville",
        "jersey city",
        "joliet",
        "kansas city",
        "knoxville",
        "lafayette",
        "lakeland",
        "lakewood",
        "lancaster",
        "laredo",
        "las vegas",
        "lexington",
        "lincoln",
        "little rock",
        "long beach",
        "los angeles",
        "louisville",
        "lubbock",
        "madison",
        "manchester",
        "mcallen",
        "mckinney",
        "memphis",
        "mesa",
        "mesquite",
        "miami",
        "milwaukee",
        "minneapolis",
        "mobile",
        "modesto",
        "montgomery",
        "moreno valley",
        "murfreesboro",
        "naperville",
        "nashville",
        "new haven",
        "new orleans",
        "new york",
        "newark",
        "newport news",
        "norfolk",
        "norman",
        "north las vegas",
        "oakland",
        "oceanside",
        "oklahoma city",
        "omaha",
        "ontario",
        "orlando",
        "overland park",
        "oxnard",
        "palmdale",
        "pasadena",
        "paterson",
        "pembroke pines",
        "peoria",
        "philadelphia",
        "phoenix",
        "pittsburgh",
        "plano",
        "pomona",
        "port st lucie",
        "portland",
        "providence",
        "provo",
        "raleigh",
        "rancho cucamonga",
        "reno",
        "richmond",
        "riverside",
        "rochester",
        "rockford",
        "sacramento",
        "salem",
        "salinas",
        "salt lake city",
        "san antonio",
        "san bernardino",
        "san diego",
        "san francisco",
        "san jose",
        "santa ana",
        "santa clara",
        "santa clarita",
        "santa rosa",
        "savannah",
        "scottsdale",
        "seattle",
        "shreveport",
        "sioux falls",
        "spokane",
        "springfield",
        "st louis",
        "st paul",
        "st petersburg",
        "stamford",
        "sterling heights",
        "stockton",
        "sunnyvale",
        "syracuse",
        "tacoma",
        "tallahassee",
        "tampa",
        "tempe",
        "thornton",
        "thousand oaks",
        "toledo",
        "topeka",
        "torrance",
        "tucson",
        "tulsa",
        "vancouver",
        "virginia beach",
        "visalia",
        "waco",
        "warren",
        "washington",
        "wichita",
        "wilmington",
        "winston salem",
        "worcester",
        "yonkers",
    }
)

NOT_A_CITY_MARKERS = (
    "park",
    "restaurant",
    "cafe",
    "coffee shop",
    "mall",
    "plaza",
    "stadium",
    "arena",
    "airport",
    "hotel",
    "motel",
    "bar",
    "club",
    "walmart",
    "target",
    "mcdonald",
    "beach",
    "pier",
    "zoo",
    "museum",
    "theme park",
    "amusement",
    "gas station",
    "truck stop",
    "campus",
    "university",
    "high school",
    "apartment",
    "condo",
    "neighborhood",
    "suburb of",
)

TIMEZONE_MARKERS = (
    "timezone",
    "time zone",
    "eastern time",
    "central time",
    "mountain time",
    "pacific time",
    "alaska time",
    "hawaii time",
)
TIMEZONE_CODES = frozenset(
    {"est", "edt", "cst", "cdt", "mst", "mdt", "pst", "pdt", "akst", "akdt", "hst", "utc", "gmt"}
)

# States are not cities. "I'm from Texas" must not become a location answer.
US_STATES = frozenset(
    {
        "alabama",
        "alaska",
        "arizona",
        "arkansas",
        "california",
        "colorado",
        "connecticut",
        "delaware",
        "florida",
        "georgia",
        "hawaii",
        "idaho",
        "illinois",
        "indiana",
        "iowa",
        "kansas",
        "kentucky",
        "louisiana",
        "maine",
        "maryland",
        "massachusetts",
        "michigan",
        "minnesota",
        "mississippi",
        "missouri",
        "montana",
        "nebraska",
        "nevada",
        "new hampshire",
        "new jersey",
        "new mexico",
        "new york",  # also a city; city list wins
        "north carolina",
        "north dakota",
        "ohio",
        "oklahoma",
        "oregon",
        "pennsylvania",
        "rhode island",
        "south carolina",
        "south dakota",
        "tennessee",
        "texas",
        "utah",
        "vermont",
        "virginia",
        "washington",  # also a city; city list wins
        "west virginia",
        "wisconsin",
        "wyoming",
    }
)

CITY_STOPWORDS = frozenset(
    {
        "monday",
        "tuesday",
        "wednesday",
        "thursday",
        "friday",
        "saturday",
        "sunday",
        "fact",
        "love",
        "here",
        "there",
        "chat",
        "home",
        "bed",
        "work",
        "school",
        "college",
        "truth",
        "life",
        "you",
        "me",
        "yeah",
        "today",
        "tonight",
        "tomorrow",
        "town",
        "city",
        "place",
    }
)


def extract_city_from_text(text: str) -> str | None:
    """First validated city in free text, or None. Days, states, and parks do not count."""
    blob = text or ""
    if not blob.strip():
        return None
    # Prefer "I'm from/in {City}" over a bare city mention.
    from .ingest import extract_cities

    found = extract_cities(blob)
    return found[0] if found else None
